# Site settings
title: Ben Cipollini
tagline: All computation, all the time.
description: > # this means to ignore newlines until "baseurl:"
  Doing science out in the open.
baseurl: ''
url:  # the base hostname & protocol for your site

gems: [jekyll-paginate]

# Contact settings
email: bcipolli@ucsd.edu
twitter_username: mrquickowl
tumblr_username: mrquickowl
github_username:  bcipolli
linkedin_url: https://www.linkedin.com/in/dr-ben-cipollini-217709b
facebook_username: bcipolli
researchgate_username: Ben_Cipollini
redbubble_username: quickowl
googlescholar_url: folio
googleplus_url: folio
wordpress_url: folio

# Build settings
markdown: kramdown

highlighter: rouge

# Pagination
paginate: 5
paginate_path: "/academia/publications/page:num"


# blog, code, pubs, projects, mentoring, about,
collections:
  projects:
    output: true
    permalink: /academia/projects/:path/
  news:
    output: true
    permalink: /academia/news/:path/
  publication-types:
    output: true
    permalink: /academia/publications/:path/

defaults:
  - scope:
      type: news
    values:
      layout: post
      document-class: news
  - scope:
      type: projects
    values:
      layout: project
      document-class: projects
  - scope:
      type: posts
    values:
      layout: post
      document-class: blog
  - scope:
      type: publications
    values:
      layout: publications-list
      document-class: projects
