# Site settings
title: Ben Cipollini
tagline: Data science for change.
baseurl: ''
url:  # the base hostname & protocol for your site

plugins: [jekyll-paginate]

# Contact settings
email: bcipollini@classy.org
twitter_username: mrquickowl
tumblr_username: mrquickowl
github_username:  bcipolli
linkedin_url: https://www.linkedin.com/in/dr-ben-cipollini-217709b
facebook_username: bcipolli
researchgate_username: Ben_Cipollini
redbubble_username: quickowl
googlescholar_url: https://scholar.google.com/citations?user=US7qORoAAAAJ
googleplus_url: https://plus.google.com/+BenCipolliniSD
resources_baseurl: http://cseweb.ucsd.edu/~bcipolli/

# Build settings
markdown: kramdown

highlighter: rouge

# Pagination
paginate: 5
paginate_path: "/academia/publications/page:num"


# blog, code, pubs, projects, mentoring, about,
collections:
  academic-projects:
    output: true
    permalink: /academia/projects/:path/
  news:
    output: true
    permalink: /academia/news/:path/
  academic-publication-types:
    output: true
    permalink: /academia/publications/:path/

defaults:
  - scope:
      type: news
    values:
      layout: post
      document-class: news
  - scope:
      type: projects
    values:
      layout: project
      document-class: projects
  - scope:
      type: posts
    values:
      layout: post
      document-class: blog
  - scope:
      type: publications
    values:
      layout: publications-list
      document-class: projects
